---
title: "TextMining - Discursos Presidenciales tidy way"
output:
  github_document: default
  pdf_document: default
  word_document: default
---
```{python}
import pandas as pd
print "hola"
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r libraries, message=FALSE, warning=FALSE}
require(tidyverse)
require(tidytext)
require(ggrepel)
require(tm)
```
```{r read_data, message=FALSE, warning=FALSE}
filenames <- list.files(".",pattern="*.txt")
discursos_raw = map(filenames,~readLines(.x,encoding="UTF-8")) %>% 
  map2(filenames, ~tibble(text=.x, docid=.y)) %>% 
  map_df(rbind)

# Replaces varios
discursos_raw = discursos_raw %>% 
  filter(text != "") %>% 
  mutate(text = gsub("SS.SS", "Sus_Señorías", text)
         ,text = gsub("SS. SS", "Sus_Señorías", text)
         )
discursos_raw 
```

```{r tyding, message=FALSE, warning=FALSE}
discursos = discursos_raw %>%
  group_by(docid) %>%
  mutate(linenumber = row_number()) %>% 
  ungroup() %>% 
  unnest_tokens(word, text) 

add.stops=c(
  "vez", "sino", "cada", "ello", "así", "sólo", "digo", 
  "que", "que,", "señorías","gobierno",
  "españa","españoles","país","ser","hacia","años",
  "debe","cualquier","año","manera","todas","mayor",
  "parte","presidenta","ustedes","vista","señora","hecho","sus")
add.stops=c("kk")
stop_words = append(add.stops, tm::stopwords("spanish"))

discursos = discursos %>% 
  filter(!word %in% stop_words) 

discursos_tfidf = discursos %>% 
  count(docid, word, sort = TRUE) %>%
  ungroup() %>% 
  bind_tf_idf(word, docid, n) %>% 
  arrange(desc(tf_idf))

discursos_tfidf %>% arrange(desc(n))
```
```{r plots words, message=FALSE, warning=FALSE}
discursos_tfidf %>% 
  group_by(docid) %>% 
  top_n(3) %>% 
  ungroup() %>% 
  arrange(docid) %>% 
  ggplot(aes(word,tf_idf, color=docid)) + 
    geom_label_repel(aes(label=word)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    theme(legend.position="bottom")
```
```{r td-idf words by doc, message=FALSE, warning=FALSE}
plots <- discursos_tfidf %>%
  group_by(docid) %>% 
  top_n(5) %>% 
  ungroup() %>% 
  mutate(word = reorder(word, tf_idf)) %>%
  split(.$docid) %>%
  map(~ ggplot(.x, aes(word,tf_idf)) + 
          geom_bar(stat="identity", aes(fill=docid)) + 
          theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
          theme(legend.position="bottom")
  )

walk(plots, print)
```

```{r tidy bigrams}
discursos_bigram_raw = discursos_raw %>%     
  unnest_tokens(bigram, text, token = "ngrams", n = 2)

add.bigramsstops=c("señora presidenta", "sus señorías")
discursos_bigram_raw = discursos_bigram_raw %>% 
  filter(!bigram %in% add.bigramsstops)
  
discursos_bigram = discursos_bigram_raw %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(!word1 %in% stop_words) %>%
  filter(!word2 %in% stop_words) %>% 
  unite(bigram, word1, word2, sep = " ") 

discursos_bigram_tfidf = discursos_bigram %>% 
  count(docid, bigram, sort = TRUE) %>%
  ungroup() %>% 
  bind_tf_idf(bigram, docid, n) %>% 
  arrange(desc(tf_idf))

discursos_bigram
```
```{r plots bigrams, message=FALSE, warning=FALSE}
discursos_bigram_tfidf %>% 
  group_by(docid) %>% 
  top_n(3) %>% 
  ungroup() %>% 
  mutate(bigram = reorder(bigram, tf_idf)) %>%
  ggplot(aes(bigram,tf_idf, color=docid)) + 
    geom_label_repel(aes(label=bigram)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    theme(legend.position="bottom")
```
```{r td-idf bigrams by doc, message=FALSE, warning=FALSE}
plots <- discursos_bigram_tfidf %>%
  group_by(docid) %>% 
  top_n(5) %>% 
  ungroup() %>% 
  mutate(bigram = reorder(bigram, tf_idf)) %>%
  split(.$docid) %>%
  map(~ ggplot(.x, aes(bigram,tf_idf)) + 
          geom_bar(stat="identity", aes(fill=docid)) + 
          theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
          theme(legend.position="bottom")
  )

walk(plots, print)
```

```{r}

```

